#!/bin/bash
#This is my first script
echo "Это мой первый скрипт!:)"
echo "Я нахожусь тут:"
pwd
echo "Создаю папку directory_script"
mkdir directory_script
echo "Захожу в папку"
cd  directory_script
echo "Создаю 3 папки d_1, d_2, d_3"
mkdir d_1 d_2 d_3
echo "Захожу в папку d_1"
cd d_1
echo "Создаю 5 файлов: 2 json, 3 txt"
touch text.txt file.txt question.json write.txt epam.json
echo "Смотрю содержимое папки d_1"
ls -a
echo "перемещаю 2 файла в папку d_2: object.json, list.txt"
mv epam.json text.txt ../d_2
echo "спасибо за внимание!:)"

